"""Initial migration

Revision ID: 00d62578dab9
Revises: 
Create Date: 2025-11-24 21:37:35.826560

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '00d62578dab9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('intake_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('initial_situation', sa.Text(), nullable=False),
    sa.Column('conversation_history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('ai_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('final_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intake_sessions_created_at'), 'intake_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_intake_sessions_is_complete'), 'intake_sessions', ['is_complete'], unique=False)
    op.create_index(op.f('ix_intake_sessions_user_id'), 'intake_sessions', ['user_id'], unique=False)
    op.create_table('emotion_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('situation', sa.Text(), nullable=False),
    sa.Column('emotions', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('intensity', sa.DECIMAL(precision=3, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('intake_session_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['intake_session_id'], ['intake_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emotion_entries_created_at'), 'emotion_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_emotion_entries_user_id'), 'emotion_entries', ['user_id'], unique=False)
    op.create_table('visualizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('style', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('insights', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('visual_elements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('gemini_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('nanobanana_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['emotion_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id')
    )
    op.create_index(op.f('ix_visualizations_created_at'), 'visualizations', ['created_at'], unique=False)
    op.create_index(op.f('ix_visualizations_status'), 'visualizations', ['status'], unique=False)
    op.create_index(op.f('ix_visualizations_user_id'), 'visualizations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visualizations_user_id'), table_name='visualizations')
    op.drop_index(op.f('ix_visualizations_status'), table_name='visualizations')
    op.drop_index(op.f('ix_visualizations_created_at'), table_name='visualizations')
    op.drop_table('visualizations')
    op.drop_index(op.f('ix_emotion_entries_user_id'), table_name='emotion_entries')
    op.drop_index(op.f('ix_emotion_entries_created_at'), table_name='emotion_entries')
    op.drop_table('emotion_entries')
    op.drop_index(op.f('ix_intake_sessions_user_id'), table_name='intake_sessions')
    op.drop_index(op.f('ix_intake_sessions_is_complete'), table_name='intake_sessions')
    op.drop_index(op.f('ix_intake_sessions_created_at'), table_name='intake_sessions')
    op.drop_table('intake_sessions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
